repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.14
  hooks:
  - id: ruff
    args: [--select, I, --cache-dir, .cache/ruff/]
  - id: ruff-format
    args: [--line-length, '120', --cache-dir, .cache/ruff/]